import bcrypt from 'bcryptjs';

const defaultSeedHash = bcrypt.hashSync('password123', 10);

// Fallback in-memory data store when local MongoDB service is offline
export const mockStore = {
  users: [
    {
      _id: 'usr_1',
      id: 'usr_1',
      name: 'Ankit Kapoor',
      email: 'recruiter@worklance.com',
      password: defaultSeedHash,
      role: 'recruiter',
      company: 'Zenith Tech',
      title: 'Talent Acquisition Lead',
      avatar: 'AK',
      createdAt: new Date().toISOString(),
    },
    {
      _id: 'usr_2',
      id: 'usr_2',
      name: 'Riya Sharma',
      email: 'seeker@worklance.com',
      password: defaultSeedHash,
      role: 'seeker',
      title: 'Frontend Engineer & UI Architect',
      company: 'NextGen Labs',
      bio: 'Product-minded frontend engineer with 4+ years of experience building high-performance web applications with React, Next.js, and TypeScript. Passionate about design systems and developer ergonomics.',
      skills: ['React', 'Next.js', 'TypeScript', 'Tailwind CSS', 'Redux Toolkit', 'GraphQL', 'Jest', 'Node.js'],
      avatar: 'RS',
      phone: '+91 98765 43210',
      location: 'Bengaluru, India',
      githubUrl: 'https://github.com',
      linkedinUrl: 'https://linkedin.com',
      portfolioUrl: 'https://riyasharma.dev',
      twitterUrl: 'https://twitter.com',
      targetRole: 'Senior Frontend Engineer / Full Stack Engineer',
      expectedSalary: '₹22,00,000 - ₹28,00,000',
      experienceYears: '4.5 Years',
      availability: 'Immediately (Notice period served)',
      workPreference: 'Remote',
      atsScore: 92,
      experience: [
        {
          id: 'exp_1',
          company: 'NextGen Labs',
          role: 'Frontend Engineer',
          location: 'Bengaluru, India',
          startDate: '2022-04',
          endDate: 'Present',
          current: true,
          description: 'Architected next-generation enterprise dashboards using Next.js 14 and TypeScript. Improved page load latency by 42% and introduced automated CI/CD testing.',
        },
        {
          id: 'exp_2',
          company: 'CloudPulse Software',
          role: 'Junior Web Developer',
          location: 'Remote',
          startDate: '2020-07',
          endDate: '2022-03',
          current: false,
          description: 'Developed reusable UI component library used across 6 web properties. Collaborated closely with design and backend teams.',
        },
      ],
      education: [
        {
          id: 'edu_1',
          school: 'National Institute of Technology, Karnataka',
          degree: 'Bachelor of Technology (B.Tech)',
          fieldOfStudy: 'Computer Science & Engineering',
          startYear: '2016',
          endYear: '2020',
          grade: '8.8 CGPA',
        },
      ],
      projects: [
        {
          id: 'proj_1',
          title: 'Worklance ATS Optimizer',
          description: 'A career platform integrating job search, ATS resume scoring, and AI interview simulators.',
          liveUrl: 'https://worklance.io',
          githubUrl: 'https://github.com/sample/worklance',
          techStack: ['Next.js 14', 'TypeScript', 'Tailwind CSS', 'MongoDB'],
        },
        {
          id: 'proj_2',
          title: 'DevCollab Realtime Editor',
          description: 'Collaborative markdown and code editor with WebSockets and syntax highlighting.',
          liveUrl: 'https://devcollab.demo',
          githubUrl: 'https://github.com/sample/devcollab',
          techStack: ['React', 'Node.js', 'Socket.io', 'Monaco Editor'],
        },
      ],
      createdAt: new Date().toISOString(),
    },
  ],
  jobs: [
    {
      _id: 'job_1',
      id: 'job_1',
      title: 'Senior Frontend Engineer (React/Next.js)',
      company: 'Zenith Tech Labs',
      companyAbout:
        'Zenith Tech Labs is a high-growth SaaS & Developer tools startup headquartered in Bengaluru. We build modern cloud infrastructures and developer productivity tools used by over 500,000 developers globally. Our engineering culture focuses on high performance, autonomy, and modern web UI craftsmanship.',
      companyIndustry: 'Software & Cloud SaaS',
      companySize: '250 - 500 employees',
      companyWebsite: 'https://zenithtechlabs.com',
      location: 'Bengaluru, India',
      type: 'Full-time',
      salary: '₹18,00,000 - ₹26,00,000 / year',
      description:
        'We are seeking an experienced Frontend Developer to lead our Web Applications team. You will architect high-performance React and Next.js platforms, build sleek design systems, and collaborate with backend developers to deliver scalable SaaS solutions.',
      responsibilities: [
        'Lead architectural decisions for frontend React/Next.js applications and component libraries.',
        'Implement responsive, pixel-perfect user interfaces with micro-animations and optimal Core Web Vitals.',
        'Optimize client-side rendering performance, state management, and API caching strategies.',
        'Mentor junior frontend engineers and conduct code reviews for high technical standards.',
      ],
      requirements: [
        '4+ years of React / Next.js experience',
        'Deep knowledge of TypeScript & modern CSS architecture',
        'Experience with state management (Zustand/Redux)',
        'Strong API integration and performance optimization skills',
      ],
      benefits: [
        'Flexible hybrid work policy (2 days office / 3 days remote)',
        'Comprehensive health insurance for self and family',
        'Annual learning budget of ₹50,000 for courses and conferences',
        'Stock options / ESOPs package',
      ],
      tags: ['React', 'Next.js', 'TypeScript', 'Frontend'],
      postedBy: 'usr_1',
      applicantCount: 14,
      createdAt: new Date().toISOString(),
    },
    {
      _id: 'job_2',
      id: 'job_2',
      title: 'Full Stack Engineer (Node.js & MongoDB)',
      company: 'Nexora Innovations',
      companyAbout:
        'Nexora Innovations is a premier fintech infrastructure firm providing high-frequency API solutions and real-time transaction processing. Based out of Mumbai with a fully distributed team across India, Nexora processes over $5B in transactions annually.',
      companyIndustry: 'Fintech & Financial Services',
      companySize: '100 - 250 employees',
      companyWebsite: 'https://nexora.io',
      location: 'Remote',
      type: 'Remote',
      salary: '₹14,00,000 - ₹20,00,000 / year',
      description:
        'Join Nexora Innovations as a Full Stack Engineer! Work on cutting-edge fintech services processing millions of API calls daily. Responsibilities include designing RESTful APIs, optimizing MongoDB queries, and implementing modern UI features.',
      responsibilities: [
        'Design and deploy resilient RESTful and GraphQL microservices in Node.js.',
        'Build real-time transaction monitoring dashboards using Next.js & Tailwind CSS.',
        'Optimize complex MongoDB aggregation pipelines and indexing for low latency.',
        'Maintain high unit and integration test coverage across cloud microservices.',
      ],
      requirements: [
        '3+ years full-stack web development',
        'Proficiency in Node.js, Express, and MongoDB Mongoose',
        'Familiarity with Cloud platforms (AWS/Vercel)',
        'Automated testing experience (Jest/Playwright)',
      ],
      benefits: [
        '100% remote work freedom with ergonomic home-office setup allowance',
        'Wellness stipend & mental health support programs',
        'Performance-linked annual bonuses',
      ],
      tags: ['Full Stack', 'Node.js', 'MongoDB', 'Remote'],
      postedBy: 'usr_1',
      applicantCount: 22,
      createdAt: new Date().toISOString(),
    },
    {
      _id: 'job_3',
      id: 'job_3',
      title: 'Product Designer (UI/UX)',
      company: 'Codeloop Studio',
      companyAbout:
        'Codeloop Studio is an award-winning digital product studio that partners with world-class tech companies and startups to design intuitive mobile apps, design systems, and web platforms. Known for human-centered design and sleek visual craft.',
      companyIndustry: 'Digital Product & Design',
      companySize: '50 - 100 employees',
      companyWebsite: 'https://codeloop.studio',
      location: 'Mumbai, India',
      type: 'Hybrid',
      salary: '₹10,00,000 - ₹15,00,000 / year',
      description:
        'Codeloop Studio is looking for a talented UI/UX Product Designer to shape the user experience across mobile and web platforms. You will conduct user research, create wireframes, interactive prototypes, and collaborate closely with product managers and engineers.',
      responsibilities: [
        'Conduct end-to-end product design cycles from user research to high-fidelity Figma components.',
        'Create interactive motion prototypes and design token systems.',
        'Collaborate with developers during sprint planning to ensure design fidelity.',
      ],
      requirements: [
        '2+ years in Product Design / UI/UX',
        'Mastery of Figma and prototyping tools',
        'Portfolio demonstrating end-to-end design process',
        'Strong visual aesthetic and micro-animation skills',
      ],
      benefits: [
        'Top-tier Apple hardware (MacBook Pro + 4K Display setup)',
        'Weekly team lunches & studio hackathons',
        'Flexible working hours',
      ],
      tags: ['UI/UX', 'Figma', 'Product Design', 'Hybrid'],
      postedBy: 'usr_1',
      applicantCount: 9,
      createdAt: new Date().toISOString(),
    },
  ],
  applications: [
    {
      _id: 'app_1',
      jobId: 'job_1',
      applicantId: 'usr_2',
      applicantName: 'Riya Sharma',
      applicantEmail: 'seeker@worklance.com',
      coverLetter: 'I have 3+ years of React experience and would love to join Zenith Tech Labs!',
      resumeUrl: 'https://drive.google.com/resume.pdf',
      status: 'Shortlisted',
      createdAt: new Date().toISOString(),
    },
  ],
  hackathons: [
    {
      _id: 'hack_1',
      title: 'Worklance Winter Hackathon 2026',
      organizer: 'Worklance Team',
      organizerBadge: 'WL',
      description:
        'Build an AI-powered hiring tool in 48 hours. Open to students and early-career developers across India.',
      prizePool: '₹3,00,000',
      status: 'Live',
      teamSize: 'Up to 4',
      tags: ['AI/ML', 'Web Dev', 'GenAI'],
      duration: '48 hrs',
      participantsCount: 1240,
      teamsCount: 180,
      deadline: '3 days left',
      createdAt: new Date().toISOString(),
    },
    {
      _id: 'hack_2',
      title: 'Zenith Labs AI Challenge',
      organizer: 'Zenith Labs',
      organizerBadge: 'ZN',
      description:
        'Create next-generation autonomous workflows using large language models and smart vector indexes.',
      prizePool: '₹1,50,000',
      status: 'Live',
      teamSize: 'Up to 4',
      tags: ['AI/ML', 'Beginner Friendly'],
      duration: '36 hrs',
      participantsCount: 890,
      teamsCount: 110,
      deadline: '2 days left',
      createdAt: new Date().toISOString(),
    },
  ],
  hrContacts: [
    {
      _id: 'hr_1',
      name: 'Ankit Kapoor',
      company: 'Zenith Tech',
      designation: 'HR Manager & Talent Lead',
      email: 'ankit.kapoor@zenithtech.com',
      linkedIn: 'https://linkedin.com/in/ankit-kapoor-hr',
      industry: 'Software & SaaS',
      city: 'Bengaluru',
      verified: true,
      createdAt: new Date().toISOString(),
    },
    {
      _id: 'hr_2',
      name: 'Pooja Verma',
      company: 'Nexora Innovations',
      designation: 'Senior Technical Recruiter',
      email: 'pooja.verma@nexora.io',
      linkedIn: 'https://linkedin.com/in/pooja-verma-recruiter',
      industry: 'Fintech',
      city: 'Mumbai',
      verified: true,
      createdAt: new Date().toISOString(),
    },
  ],
};
